### ISSUE TITLE
Master Assets

### ISSUE THREAD

**Issue by jsimmons1980** [bnb-chain/token-bind-tool#6]
Token / Coin  balances

**Comment by raul836** [comment]
)
{
    "name": "VBNB",
    "type": "BEP20",
    "symbol": "VBNB",
    "decimals": 4,
    "website": "https://tokenworkcom.wordpress.com/#jp-carousel-50",
    "description": "VBNB es un token descentralizado echo en bcscan es un meme Coín ",
    "explorer": "https://bscscan.com/token/0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "status": "active",
    "id": "0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "github",
            "url": "https://github.com/raul836/assets"
        },
        {
            "name": "telegrama",
            "url": "@ReporVBNB"
        },
        {
            "name": "papel blanco",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/user/Ral633/"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "medio",
            "url": "https://medium.com/@rauldeleon_32774"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/profile.php?id=100083171714836&mibextid=ZbWKwL"
        },
        {
            "name": "YouTube",
            "url": "https://youtube.com/@VBNBCHAIN"
        },
        {
            "name": "Blog",
            "url": "https://www.geckoterminal.com/es/bsc/pools/0x40968913544195fc0609f21a514cf26c30fbc7f7"
        },
        {
            "name": "documentos",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "telegram",
            "url": "https://t.me/"
        },
        {
            "name": "gorjeo",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "telegram_news",
            "url": "https://t.me/@ReporVBNB"
        },
        {
            "name": "blog",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0
{
    "name": "VBNB",
    "type": "BEP20",
    "symbol": "VBNB",
    "decimals": 4,
    "website": "https://tokenworkcom.wordpress.com/#jp-carousel-50",
    "description": "VBNB es un token descentralizado echo en bcscan es un meme Coín ",
    "explorer": "https://bscscan.com/token/0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "status": "active",
    "id": "0x7E20f650Cd25B72813280933f2754d651601AE6B",
    "links": [
        {
            "name": "twitter",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "github",
            "url": "https://github.com/raul836/assets"
        },
        {
            "name": "telegrama",
            "url": "@ReporVBNB"
        },
        {
            "name": "papel blanco",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "Reddit",
            "url": "https://www.reddit.com/user/Ral633/"
        },
        {
            "name": "coinmarketcap",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "medio",
            "url": "https://medium.com/@rauldeleon_32774"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/profile.php?id=100083171714836&mibextid=ZbWKwL"
        },
        {
            "name": "YouTube",
            "url": "https://youtube.com/@VBNBCHAIN"
        },
        {
            "name": "Blog",
            "url": "https://www.geckoterminal.com/es/bsc/pools/0x40968913544195fc0609f21a514cf26c30fbc7f7"
        },
        {
            "name": "documentos",
            "url": "https://tokenworkcom.wordpress.com/#jp-carousel-50"
        },
        {
            "name": "telegram",
            "url": "https://t.me/"
        },
        {
            "name": "gorjeo",
            "url": "https://twitter.com/RaulAra78303627"
        },
        {
            "name": "telegram_news",
            "url": "https://t.me/@ReporVBNB"
        },
        {
            "name": "blog",
            "url": "https://coinmarketcap.com/dexscan/bsc/0x40968913544195fc0609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "foro",
            "url": "0x40968913544195fc0609f21a514cf26c30fbc7f7"
        }
    ],
    "tags": [
        "26",
        "memes"
    ]
} 
< centro >< img src = ' [url=https://ibb.co/yssMtBT][img]https://i.ibb.co/yssMtBT/image-1-2-1.png][/url] ' altura = "200" ></ centro609f21a514cf26c30fbc7f7/"
        },
        {
            "name": "foro",
            "url": "0x40968913544195fc0609f21a514cf26c30fbc7f7"
        }
    ],
    "tags": [
        "26",
        "memes"
    ]
} 
< centro >< img src = ' [url=https://ibb.co/yssMtBT][img]https://i.ibb.co/yssMtBT/image-1-2-1.png][/url] ' altura = "200" ></ centro)

**Comment by ByPalmy** [comment]
![ IMG_0851](https://github.com/bnb-chain/token-bind-tool/assets/171250193/bda9bab6-273b-4307-9111-933986ff75e3)  #[](![IMG_0859](https://github.com/bnb-chain/token-bind-tool/assets/171250193/a302f5ad-d681-496c-8e80-9bed73cc34c0))) ![ IMG_0858](https://github.com/bnb-chain/token-bind-tool/assets/171250193/052ed631-5b0a-4477-beaa-18bb503f8410) ![ IMG_0850](https://github.com/bnb-chain/token-bind-tool/assets/171250193/e0dfb43b-0ded-4513-b62d-caff35be2c98) ![ IMG_0821](https://github.com/bnb-chain/token-bind-tool/assets/171250193/7763aeea-acb7-4909-8b70-4760d7167532) ![ IMG_0814](https://github.com/bnb-chain/token-bind-tool/assets/171250193/ded6f41d-f7d1-48c6-861c-3be6cb89298a) ![ IMG_0832](https://github.com/bnb-chain/token-bind-tool/assets/171250193/890f1613-95b6-4152-ad91-1a2f4b061a3c) ![ IMG_0831](https://github.com/bnb-chain/token-bind-tool/assets/171250193/e1151df7-005c-4ddb-b859-11ddb77341aa) ![ IMG_0827](https://github.com/bnb-chain/token-bind-tool/assets/171250193/1bdf4253-d207-4cd7-928f-d54a840a0af2) ![ IMG_0810](https://github.com/bnb-chain/token-bind-tool/assets/171250193/9d7fd5ba-65aa-491a-b1c9-48584a9a075a) `` ![ IMG_0810](https://github.com/bnb-chain/token-bind-tool/assets/171250193/5489891f-1c21-45d7-be40-5c44772bc6fe) ![ IMG_0826](https://github.com/bnb-chain/token-bind-tool/assets/171250193/c85b5c10-fd0d-4c91-8c00-1f1730ddadf3) ![ IMG_0825](https://github.com/bnb-chain/token-bind-tool/assets/171250193/6e62d442-9551-41bc-b677-ccbf9da7e52e) ![ IMG_0824](https://github.com/bnb-chain/token-bind-tool/assets/171250193/3f5a34d1-2f50-4e03-803d-0cbb8b5988d2) ![ IMG_0823](https://github.com/bnb-chain/token-bind-tool/assets/171250193/1318c9b2-2511-4fa4-9735-58ff25bbd02d) ![ IMG_0820](https://github.com/bnb-chain/token-bind-tool/assets/171250193/4ce77df8-5add-441c-b34d-3f51b1409aea) ![ IMG_0819](https://github.com/bnb-chain/token-bind-tool/assets/171250193/51533352-4bd9-4874-b2c0-886bc0f948bf) ![ IMG_0820](https://github.com/bnb-chain/token-bind-tool/assets/171250193/16f657fe-cb96-44d7-bc83-d992079e676f) ![ IMG_0818](https://github.com/bnb-chain/token-bind-tool/assets/171250193/6f14ec5d-a67b-42b7-b9e2-1a3ec59bb29b) ![ IMG_0814](https://github.com/bnb-chain/token-bind-tool/assets/171250193/bead8c67-5454-4154-a288-dcef93921286) ![ IMG_0816](https://github.com/bnb-chain/token-bind-tool/assets/171250193/03c981fa-c119-4895-86e8-faa4e9be5642) ![ IMG_0815](https://github.com/bnb-chain/token-bind-tool/assets/171250193/4bc7ef55-c4f5-436d-98db-46dc93a963b5) ![ IMG_0813](https://github.com/bnb-chain/token-bind-tool/assets/171250193/eb173acc-cdcf-4897-8fc4-604bfbc157d3) ![ IMG_0849](https://github.com/bnb-chain/token-bind-tool/assets/171250193/c6bdf519-5cef-4125-86c4-779af646eaef) ![ IMG_0831](https://github.com/bnb-chain/token-bind-tool/assets/171250193/ddbe325c-3e9e-413f-a6a8-d2ec0f288108)
